# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kruskal_mst_c <- function(x, maximum = FALSE, verbose = FALSE) {
    .Call('_spice_kruskal_mst_c', PACKAGE = 'spice', x, maximum, verbose)
}

make_symmetric <- function(x, method = "L") {
    invisible(.Call('_spice_make_symmetric', PACKAGE = 'spice', x, method))
}

get_lower_triangle_vector <- function(x, diagonal = FALSE, bycol = TRUE) {
    .Call('_spice_get_lower_triangle_vector', PACKAGE = 'spice', x, diagonal, bycol)
}

set_lower_triangle_vector <- function(x, lt, bycol = TRUE) {
    invisible(.Call('_spice_set_lower_triangle_vector', PACKAGE = 'spice', x, lt, bycol))
}

replace_NA_in_matrix <- function(x, value) {
    invisible(.Call('_spice_replace_NA_in_matrix', PACKAGE = 'spice', x, value))
}

set_absolute_values_in_matrix <- function(x) {
    invisible(.Call('_spice_set_absolute_values_in_matrix', PACKAGE = 'spice', x))
}

set_diag <- function(x, value) {
    invisible(.Call('_spice_set_diag', PACKAGE = 'spice', x, value))
}

update_rankprod_matrix <- function(rankprod, ranks) {
    invisible(.Call('_spice_update_rankprod_matrix', PACKAGE = 'spice', rankprod, ranks))
}

from_sampled_assoc_matrix_to_all_assoc_vector <- function(sampled_assoc, all_genes, from_dist = FALSE) {
    .Call('_spice_from_sampled_assoc_matrix_to_all_assoc_vector', PACKAGE = 'spice', sampled_assoc, all_genes, from_dist)
}

get_rankprod_vector_from_matrix <- function(rankprod) {
    .Call('_spice_get_rankprod_vector_from_matrix', PACKAGE = 'spice', rankprod)
}

